name: Test und deployment von Mehrwertsteuer

on : push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v5
            
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with: 
                node-version: "20"

            - name: install dependencies
              run: |
                cd ha25082025 
                npm install

            - name: test
              run: |
                cd ha25082025
                npm test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v5

            - name: ssh setup
              run: | 
                mkdir -p ~/.ssh
                echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/meinPrivateKey
                chmod 400 ~/.ssh/meinPrivateKey
                ssh-keyscan -H ${{secrets.EC2_IP}}  >> ~/.ssh/known_hosts    
            
            - name: kopiere mwst.js zu ec2 maschine
              run: |
                scp -i ~/.ssh/meinPrivateKey testing-example/math.js ubuntu@${{secrets.EC2_IP}}:/home/ubuntu
