name: Test und deployment von Mehrwertsteuer

on : push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: message_from_slack
              uses: slackapi/slack-github-action@v2.1.1
              with:
                webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
                webhook-type: incoming-webhook
                payload: |
                  text: "Pipeline wurde soeben gestartet. Pipeline: ${{github.workflow}}"

            - name: checkout
              uses: actions/checkout@v5
            
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with: 
                node-version: "20"

            - name: install dependencies
              run: |
                cd HA25082025 
                npm install

            - name: test
              run: |
                cd HA25082025
                npm test

            - name: coverage upload
              uses: actions/upload-artifact@v4
              with: 
                name: coverage-report
                path: HA25082025/coverage

            - name: slack_success
              if: ${{success()}}
              uses: slackapi/slack-github-action@v2.1.1
              with:
                webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
                webhook-type: incoming-webhook
                payload: |
                  text: "Job erfolgreich"

            - name: slack_failure
              if: ${{failure()}}
              uses: slackapi/slack-github-action@v2.1.1
              with:
                webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
                webhook-type: incoming-webhook
                payload: |
                  text: "Job fehlgeschlagen"
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v5

            - name: ssh setup
              run: | 
                mkdir -p ~/.ssh
                echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/meinPrivateKey
                chmod 400 ~/.ssh/meinPrivateKey
                ssh-keyscan -H ${{secrets.EC2_IP}}  >> ~/.ssh/known_hosts    
            
            - name: kopiere mwst.js zu ec2 maschine
              run: |
                scp -i ~/.ssh/meinPrivateKey ./HA25082025/mwst.js ubuntu@${{secrets.EC2_IP}}:/home/ubuntu
